name: Build Tailscale for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天运行一次

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ] # Go 版本，可根据需要修改
        platform: [ 'arm', 'arm64' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make git gcc

    - name: Build Tailscale
      run: |
        make clean
        env GOOS=linux GOARCH=${{ matrix.platform }} make tailscale tailscaled

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: tailscale-${{ matrix.platform }}
        path: |
          ./cmd/tailscale/tailscale
          ./cmd/tailscaled/tailscaled
